### ISSUE TITLE
Polish Propulsion

### ISSUE THREAD

**Issue by TomLonergan03** [Hyp-ed/hyped-2022#32]
All files need checked for basic issues

Files assigned:
- [ ] state_processor.cpp  @maryk-123
- [ ] state_processor.hpp @maryk-123
- [x] file_reader.cpp @TomLonergan03 
- [x] file_reader.hpp @TomLonergan03 
- [x] RPM_regulator.hpp @TomLonergan03 
- [x] RPM_regulator.cpp @TomLonergan03 
- [x] controller.cpp @TomLonergan03 
- [x] controller.hpp @TomLonergan03 
- [x] controller_interface.hpp @TomLonergan03 
- [x] main.cpp @RoxieBethyl 
- [x] main.hpp @RoxieBethyl 
- [x] deal with issue #35 @TomLonergan03 
- [x] fake_controller.cpp @TomLonergan03 
- [x] fake_controller.hpp @TomLonergan03 

Unassigned:

**Comment by MiltFra** [comment]
This should fix #32 as well.
